const provinces = [
  { value: "all", label: "Tất cả tỉnh thành" },
  { value: "AG", label: "An Giang" },
  { value: "BV", label: "Bà Rịa - Vũng Tàu" },
  { value: "BL", label: "Bạc Liêu" },
  { value: "BK", label: "Bắc Kạn" },
  { value: "BG", label: "Bắc Giang" },
  { value: "BN", label: "Bắc Ninh" },
  { value: "BT", label: "Bến Tre" },
  { value: "BD", label: "Bình Dương" },
  { value: "BDI", label: "Bình Định" },
  { value: "BP", label: "Bình Phước" },
  { value: "BT", label: "Bình Thuận" },
  { value: "CM", label: "Cà Mau" },
  { value: "CB", label: "Cao Bằng" },
  { value: "CT", label: "Cần Thơ" },
  { value: "DN", label: "Đà Nẵng" },
  { value: "DL", label: "Đắk Lắk" },
  { value: "DNO", label: "Đắk Nông" },
  { value: "DB", label: "Điện Biên" },
  { value: "DNA", label: "Đồng Nai" },
  { value: "DT", label: "Đồng Tháp" },
  { value: "GL", label: "Gia Lai" },
  { value: "HG", label: "Hà Giang" },
  { value: "HNA", label: "Hà Nam" },
  { value: "HN", label: "Hà Nội" },
  { value: "HT", label: "Hà Tĩnh" },
  { value: "HD", label: "Hải Dương" },
  { value: "HP", label: "Hải Phòng" },
  { value: "HGI", label: "Hậu Giang" },
  { value: "HB", label: "Hòa Bình" },
  { value: "HCM", label: "Thành phố Hồ Chí Minh" },
  { value: "HY", label: "Hưng Yên" },
  { value: "KH", label: "Khánh Hòa" },
  { value: "KG", label: "Kiên Giang" },
  { value: "KT", label: "Kon Tum" },
  { value: "LC", label: "Lai Châu" },
  { value: "LS", label: "Lạng Sơn" },
  { value: "LCA", label: "Lào Cai" },
  { value: "LD", label: "Lâm Đồng" },
  { value: "LA", label: "Long An" },
  { value: "ND", label: "Nam Định" },
  { value: "NA", label: "Nghệ An" },
  { value: "NB", label: "Ninh Bình" },
  { value: "NT", label: "Ninh Thuận" },
  { value: "PT", label: "Phú Thọ" },
  { value: "PY", label: "Phú Yên" },
  { value: "QB", label: "Quảng Bình" },
  { value: "QNA", label: "Quảng Nam" },
  { value: "QNG", label: "Quảng Ngãi" },
  { value: "QN", label: "Quảng Ninh" },
  { value: "QT", label: "Quảng Trị" },
  { value: "ST", label: "Sóc Trăng" },
  { value: "SL", label: "Sơn La" },
  { value: "TN", label: "Tây Ninh" },
  { value: "TB", label: "Thái Bình" },
  { value: "TNG", label: "Thái Nguyên" },
  { value: "TH", label: "Thanh Hóa" },
  { value: "TTH", label: "Thừa Thiên Huế" },
  { value: "TG", label: "Tiền Giang" },
  { value: "TV", label: "Trà Vinh" },
  { value: "TQ", label: "Tuyên Quang" },
  { value: "VL", label: "Vĩnh Long" },
  { value: "VP", label: "Vĩnh Phúc" },
  { value: "YB", label: "Yên Bái" },
];
const provinceMap = new Map([
  ["AG", "An Giang"],
  ["BV", "Bà Rịa - Vũng Tàu"],
  ["BL", "Bạc Liêu"],
  ["BK", "Bắc Kạn"],
  ["BG", "Bắc Giang"],
  ["BN", "Bắc Ninh"],
  ["BT", "Bến Tre"],
  ["BD", "Bình Dương"],
  ["BDI", "Bình Định"],
  ["BP", "Bình Phước"],
  ["BT", "Bình Thuận"],
  ["CM", "Cà Mau"],
  ["CB", "Cao Bằng"],
  ["CT", "Cần Thơ"],
  ["DN", "Đà Nẵng"],
  ["DL", "Đắk Lắk"],
  ["DNO", "Đắk Nông"],
  ["DB", "Điện Biên"],
  ["DNA", "Đồng Nai"],
  ["DT", "Đồng Tháp"],
  ["GL", "Gia Lai"],
  ["HG", "Hà Giang"],
  ["HNA", "Hà Nam"],
  ["HN", "Hà Nội"],
  ["HT", "Hà Tĩnh"],
  ["HD", "Hải Dương"],
  ["HP", "Hải Phòng"],
  ["HGI", "Hậu Giang"],
  ["HB", "Hòa Bình"],
  ["HCM", "Thành phố Hồ Chí Minh"],
  ["HY", "Hưng Yên"],
  ["KH", "Khánh Hòa"],
  ["KG", "Kiên Giang"],
  ["KT", "Kon Tum"],
  ["LC", "Lai Châu"],
  ["LS", "Lạng Sơn"],
  ["LCA", "Lào Cai"],
  ["LD", "Lâm Đồng"],
  ["LA", "Long An"],
  ["ND", "Nam Định"],
  ["NA", "Nghệ An"],
  ["NB", "Ninh Bình"],
  ["NT", "Ninh Thuận"],
  ["PT", "Phú Thọ"],
  ["PY", "Phú Yên"],
  ["QB", "Quảng Bình"],
  ["QNA", "Quảng Nam"],
  ["QNG", "Quảng Ngãi"],
  ["QN", "Quảng Ninh"],
  ["QT", "Quảng Trị"],
  ["ST", "Sóc Trăng"],
  ["SL", "Sơn La"],
  ["TN", "Tây Ninh"],
  ["TB", "Thái Bình"],
  ["TNG", "Thái Nguyên"],
  ["TH", "Thanh Hóa"],
  ["TTH", "Thừa Thiên Huế"],
  ["TG", "Tiền Giang"],
  ["TV", "Trà Vinh"],
  ["TQ", "Tuyên Quang"],
  ["VL", "Vĩnh Long"],
  ["VP", "Vĩnh Phúc"],
  ["YB", "Yên Bái"],
]);

export default provinces;
